version: "2"

linters:
  settings:
    govet:
      settings:
        printf:
          funcs:
            - (*github.com/sirupsen/logrus.Entry).Debugf
            - (*github.com/sirupsen/logrus.Entry).Infof
            - (*github.com/sirupsen/logrus.Entry).Logf
            - (*github.com/sirupsen/logrus.Entry).Warnf
            - (*github.com/sirupsen/logrus.Entry).Errorf
            - (*github.com/sirupsen/logrus.Entry).Fatalf
            - github.com/sirupsen/logrus.Debugf
            - github.com/sirupsen/logrus.Infof
            - github.com/sirupsen/logrus.Logf
            - github.com/sirupsen/logrus.Warnf
            - github.com/sirupsen/logrus.Errorf
            - github.com/sirupsen/logrus.Fatalf
    staticcheck:
      checks:
        - "all"
        # excluded by default
        #- "-ST1000"
        #- "-ST1003" 
        #- "-ST1016"
        #- "-ST1020"
        #- "-ST1021"
        #- "-ST1022"
        # Allow `createIsSet := false` initialization for clarity
        - "-QF1007"

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: _test\.go
        text: lmdbenv.KVString struct literal uses unkeyed fields
    paths:
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - powerdns.com
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$

