#!/bin/sh

function autogen_warning() {
    echo
    echo "<!-- ======================================================= -->"
    echo "<!-- AUTOMATICALLY GENERATED BY update-docs.sh - DO NOT EDIT -->"
    echo "<!-- ======================================================= -->"
    echo
}

(
    autogen_warning
    echo "# Commands"
    echo
    echo 'This page describes the various subcommands supported by the `lightningstream` command.'
    echo
    autogen_warning
    go run ./cmd/lightningstream --config docker/pdns/lightningstream.yaml docs
    autogen_warning
) > docs/commands.md

(
    autogen_warning
    # Replace a string with contents of a file
    # https://stackoverflow.com/a/25557287/297793
    awk 'NR==FNR { a[n++]=$0; next } 
    /__CONFIG__/ { for (i=0;i<n;++i) print a[i]; next }
    1' example.yaml docs/configuration.template.md 
    autogen_warning
) > docs/configuration.md


