#!/bin/sh

function autogen_warning() {
    echo
    echo "<!-- ======================================================= -->"
    echo "<!-- AUTOMATICALLY GENERATED BY update-docs.sh - DO NOT EDIT -->"
    echo "<!-- ======================================================= -->"
    echo
}

(
    autogen_warning
    echo "# Commands"
    echo
    echo 'This page describes the various subcommands supported by the `lightningstream` command.'
    echo
    autogen_warning
    go run ./cmd/lightningstream --config docker/pdns/lightningstream.yaml docs
    autogen_warning
) > docs/commands.md
