instance: instance-${instance}
lmdbs:
  main:
    path: /lmdb/instance-${instance}/db
    schema_tracks_changes: true
    options:
      no_subdir: true
      create: true
  shard:
    path: /lmdb/instance-${instance}/db-0
    schema_tracks_changes: true
    options:
      no_subdir: true
      create: true

sweeper:
  # We want to run in the devenv, but we do not want anything to be
  # actually cleaned, because we do not have the right consistency
  # guarantees here. The devenv is expected to only be spun up occasionally.
  enabled: true
  retention_days: 3650  # 10 years
  interval: 6h
  first_interval: 1m
  lock_duration: 50ms
  release_duration: 50ms

storage:
  #type: fs
  type: s3
  options:
    #root_path: /snapshots
    access_key: minioadmin
    secret_key: minioadmin
    region: us-east-1
    bucket: lightningstream
    endpoint_url: http://minio:9000
    create_bucket: true
  cleanup:
    enabled: true
    interval: 15m
    must_keep_interval: 24h
    remove_old_instances_interval: 168h

http:
  address: ":8500"

