package lmdbstats

import (
	"time"

	"github.com/PowerDNS/lmdb-go/lmdb"
)

// Stats is the root statistics object generated by a collection run
type Stats struct {
	Name  string    `json:"name"` // Name to use in metrics labels
	Time  time.Time `json:"time"`
	TxnID uint64    `json:"txn_id"` // Actual TxnID this reflects

	Path     string `json:"path"`
	FileSize int64  `json:"file_size"`

	EnvInfo lmdb.EnvInfo `json:"env_info"`
	DBIs    []DBIStats   `json:"dbis"`

	UsedPages uint64 `json:"used_pages"`
	UsedBytes uint64 `json:"used_bytes"`

	// UsedFraction is the fraction of the LMDB pages in use
	UsedFraction float64 `json:"used_fraction"`
	// AllocatedFraction is the fraction of pages allocated on disk
	AllocatedFraction float64 `json:"allocated_fraction"`

	// UnallocatedPages is the number of pages not yet allocated. Once this
	// approaches zero, you may not be able to free old pages, because
	// freeing pages requires copy-on-write of a btree structure.
	UnallocatedPages uint64 `json:"unallocated_pages"`
	UnallocatedBytes uint64 `json:"unallocated_bytes"`

	// Memory contains info fron /proc/self/smaps on Linux, if enabled.
	// On some systems fetching this can be a heavy operation, so it is
	// disabled by defaults.
	Memory *MemoryStats `json:"memory,omitempty"`

	// TODO: reader info with timestamps
	// TODO: env flags
}

type EnvInfo struct {
	// From lmdb.EnvInfo, with extra json tags
	MapSize    int64 `json:"map_size"`    // Size of the data memory map
	LastPNO    int64 `json:"last_pno"`    // ID of the last used page
	LastTxnID  int64 `json:"last_txn_id"` // ID of the last committed transaction
	MaxReaders uint  `json:"max_readers"` // maximum number of readers for the environment
	NumReaders uint  `json:"num_readers"` // number of readers using the environment
}

type DBIStats struct {
	Name string // DBI name

	// lmdb.Stat fields
	PageSize      uint   `json:"page_size"`      // Size of a database page. This is currently the same for all databases.
	Depth         uint   `json:"depth"`          // Depth (height) of the B-tree
	BranchPages   uint64 `json:"branch_pages"`   // Number of internal (non-leaf) pages
	LeafPages     uint64 `json:"leaf_pages"`     // Number of leaf pages
	OverflowPages uint64 `json:"overflow_pages"` // Number of overflow pages
	Entries       uint64 `json:"entries"`        // Number of data items

	// Extra fields
	UsedPages    uint64  `json:"used_pages"`
	UsedBytes    uint64  `json:"used_bytes"` // bytes, equals TotalPages * PSize
	UsedFraction float64 `json:"used_fraction"`

	// EntriesPerPage is the average number of entries per leaf or overflow page
	// rounded down to an integer. The reason only these two types of pages are
	// considered is that this is where the actual item data is stored. This
	// numbers tells you how compact the data is packed. With fragmentation
	// the number will likely go down over time.
	EntriesPerPage int `json:"entries_per_page"`
}

type MemoryStats struct {
	Smaps map[string]int64 `json:"smaps"` // Linux: info from /proc/self/smaps
}
