// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: snapshot.proto

package gogosnapshot

import (
	bytes "bytes"
	encoding_binary "encoding/binary"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type KV struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	TimestampNano        uint64   `protobuf:"fixed64,3,opt,name=timestampNano,proto3" json:"timestampNano,omitempty"`
	Flags                uint32   `protobuf:"varint,4,opt,name=flags,proto3" json:"flags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
}

func (m *KV) Reset()         { *m = KV{} }
func (m *KV) String() string { return proto.CompactTextString(m) }
func (*KV) ProtoMessage()    {}
func (*KV) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c8aab8e59648e0b, []int{0}
}
func (m *KV) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *KV) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_KV.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *KV) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KV.Merge(m, src)
}
func (m *KV) XXX_Size() int {
	return m.Size()
}
func (m *KV) XXX_DiscardUnknown() {
	xxx_messageInfo_KV.DiscardUnknown(m)
}

var xxx_messageInfo_KV proto.InternalMessageInfo

func (m *KV) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *KV) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *KV) GetTimestampNano() uint64 {
	if m != nil {
		return m.TimestampNano
	}
	return 0
}

func (m *KV) GetFlags() uint32 {
	if m != nil {
		return m.Flags
	}
	return 0
}

type DBI struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Entries              []KV     `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries"`
	Flags                uint64   `protobuf:"varint,3,opt,name=flags,proto3" json:"flags,omitempty"`
	Transform            string   `protobuf:"bytes,4,opt,name=transform,proto3" json:"transform,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
}

func (m *DBI) Reset()         { *m = DBI{} }
func (m *DBI) String() string { return proto.CompactTextString(m) }
func (*DBI) ProtoMessage()    {}
func (*DBI) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c8aab8e59648e0b, []int{1}
}
func (m *DBI) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DBI) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DBI.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DBI) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBI.Merge(m, src)
}
func (m *DBI) XXX_Size() int {
	return m.Size()
}
func (m *DBI) XXX_DiscardUnknown() {
	xxx_messageInfo_DBI.DiscardUnknown(m)
}

var xxx_messageInfo_DBI proto.InternalMessageInfo

func (m *DBI) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DBI) GetEntries() []KV {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *DBI) GetFlags() uint64 {
	if m != nil {
		return m.Flags
	}
	return 0
}

func (m *DBI) GetTransform() string {
	if m != nil {
		return m.Transform
	}
	return ""
}

type Snapshot struct {
	FormatVersion        uint32        `protobuf:"varint,1,opt,name=formatVersion,proto3" json:"formatVersion,omitempty"`
	CompatVersion        uint32        `protobuf:"varint,4,opt,name=compatVersion,proto3" json:"compatVersion,omitempty"`
	Meta                 Snapshot_Meta `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta"`
	Databases            []*DBI        `protobuf:"bytes,3,rep,name=databases,proto3" json:"databases,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
}

func (m *Snapshot) Reset()         { *m = Snapshot{} }
func (m *Snapshot) String() string { return proto.CompactTextString(m) }
func (*Snapshot) ProtoMessage()    {}
func (*Snapshot) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c8aab8e59648e0b, []int{2}
}
func (m *Snapshot) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Snapshot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Snapshot.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Snapshot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Snapshot.Merge(m, src)
}
func (m *Snapshot) XXX_Size() int {
	return m.Size()
}
func (m *Snapshot) XXX_DiscardUnknown() {
	xxx_messageInfo_Snapshot.DiscardUnknown(m)
}

var xxx_messageInfo_Snapshot proto.InternalMessageInfo

func (m *Snapshot) GetFormatVersion() uint32 {
	if m != nil {
		return m.FormatVersion
	}
	return 0
}

func (m *Snapshot) GetCompatVersion() uint32 {
	if m != nil {
		return m.CompatVersion
	}
	return 0
}

func (m *Snapshot) GetMeta() Snapshot_Meta {
	if m != nil {
		return m.Meta
	}
	return Snapshot_Meta{}
}

func (m *Snapshot) GetDatabases() []*DBI {
	if m != nil {
		return m.Databases
	}
	return nil
}

type Snapshot_Meta struct {
	GenerationID         string   `protobuf:"bytes,1,opt,name=generationID,proto3" json:"generationID,omitempty"`
	InstanceID           string   `protobuf:"bytes,2,opt,name=instanceID,proto3" json:"instanceID,omitempty"`
	Hostname             string   `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	LmdbTxnID            int64    `protobuf:"varint,4,opt,name=lmdbTxnID,proto3" json:"lmdbTxnID,omitempty"`
	TimestampNano        uint64   `protobuf:"fixed64,5,opt,name=timestampNano,proto3" json:"timestampNano,omitempty"`
	DatabaseName         string   `protobuf:"bytes,7,opt,name=databaseName,proto3" json:"databaseName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
}

func (m *Snapshot_Meta) Reset()         { *m = Snapshot_Meta{} }
func (m *Snapshot_Meta) String() string { return proto.CompactTextString(m) }
func (*Snapshot_Meta) ProtoMessage()    {}
func (*Snapshot_Meta) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c8aab8e59648e0b, []int{2, 0}
}
func (m *Snapshot_Meta) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Snapshot_Meta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Snapshot_Meta.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Snapshot_Meta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Snapshot_Meta.Merge(m, src)
}
func (m *Snapshot_Meta) XXX_Size() int {
	return m.Size()
}
func (m *Snapshot_Meta) XXX_DiscardUnknown() {
	xxx_messageInfo_Snapshot_Meta.DiscardUnknown(m)
}

var xxx_messageInfo_Snapshot_Meta proto.InternalMessageInfo

func (m *Snapshot_Meta) GetGenerationID() string {
	if m != nil {
		return m.GenerationID
	}
	return ""
}

func (m *Snapshot_Meta) GetInstanceID() string {
	if m != nil {
		return m.InstanceID
	}
	return ""
}

func (m *Snapshot_Meta) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *Snapshot_Meta) GetLmdbTxnID() int64 {
	if m != nil {
		return m.LmdbTxnID
	}
	return 0
}

func (m *Snapshot_Meta) GetTimestampNano() uint64 {
	if m != nil {
		return m.TimestampNano
	}
	return 0
}

func (m *Snapshot_Meta) GetDatabaseName() string {
	if m != nil {
		return m.DatabaseName
	}
	return ""
}

func init() {
	proto.RegisterType((*KV)(nil), "gogosnapshot.KV")
	proto.RegisterType((*DBI)(nil), "gogosnapshot.DBI")
	proto.RegisterType((*Snapshot)(nil), "gogosnapshot.Snapshot")
	proto.RegisterType((*Snapshot_Meta)(nil), "gogosnapshot.Snapshot.Meta")
}

func init() { proto.RegisterFile("snapshot.proto", fileDescriptor_0c8aab8e59648e0b) }

var fileDescriptor_0c8aab8e59648e0b = []byte{
	// 430 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x41, 0x8e, 0xd3, 0x30,
	0x14, 0x86, 0xeb, 0x26, 0xd3, 0x36, 0x6f, 0x5a, 0x54, 0x2c, 0x16, 0x51, 0x41, 0x26, 0x8a, 0x58,
	0x74, 0x15, 0xd0, 0x20, 0x2e, 0x10, 0x65, 0x13, 0x46, 0xcc, 0xc2, 0xa0, 0xee, 0xdd, 0x19, 0x4f,
	0x1a, 0xd1, 0xd8, 0x51, 0x6c, 0x10, 0xac, 0xb8, 0x02, 0x1b, 0xee, 0xc0, 0x51, 0x66, 0x39, 0x0b,
	0xd6, 0x68, 0x26, 0xbd, 0x04, 0x4b, 0x64, 0x27, 0x21, 0x8d, 0x98, 0x5d, 0xde, 0xe7, 0x67, 0xff,
	0xff, 0xff, 0xf2, 0xe0, 0x91, 0x12, 0xac, 0x54, 0x3b, 0xa9, 0xa3, 0xb2, 0x92, 0x5a, 0xe2, 0x79,
	0x26, 0x33, 0xd9, 0xb1, 0x15, 0x98, 0xaa, 0x39, 0x09, 0x77, 0x30, 0x3e, 0xdf, 0xe0, 0x25, 0x38,
	0x1f, 0xf9, 0x57, 0x1f, 0x05, 0x68, 0x3d, 0xa7, 0xe6, 0x13, 0x3f, 0x81, 0x93, 0xcf, 0x6c, 0xff,
	0x89, 0xfb, 0x63, 0xcb, 0x9a, 0x02, 0xbf, 0x80, 0x85, 0xce, 0x0b, 0xae, 0x34, 0x2b, 0xca, 0x0b,
	0x26, 0xa4, 0xef, 0x04, 0x68, 0x3d, 0xa1, 0x43, 0x68, 0xee, 0x5e, 0xef, 0x59, 0xa6, 0x7c, 0x37,
	0x40, 0xeb, 0x05, 0x6d, 0x8a, 0xf0, 0x1b, 0x38, 0x49, 0x9c, 0x62, 0x0c, 0xae, 0x60, 0x05, 0xb7,
	0x5a, 0x1e, 0xb5, 0xdf, 0xf8, 0x15, 0x4c, 0xb9, 0xd0, 0x55, 0xce, 0x95, 0x3f, 0x0e, 0x9c, 0xf5,
	0xe9, 0xd9, 0x32, 0x3a, 0x36, 0x1c, 0x9d, 0x6f, 0x62, 0xf7, 0xe6, 0xf7, 0xf3, 0x11, 0xed, 0xda,
	0x7a, 0x09, 0x63, 0xc0, 0x6d, 0x25, 0xf0, 0x33, 0xf0, 0x74, 0xc5, 0x84, 0xba, 0x96, 0x55, 0x61,
	0xc5, 0x3d, 0xda, 0x83, 0xf0, 0x87, 0x03, 0xb3, 0xf7, 0xed, 0x93, 0x26, 0x89, 0x81, 0x4c, 0x6f,
	0x78, 0xa5, 0x72, 0x29, 0xac, 0x9f, 0x05, 0x1d, 0x42, 0xd3, 0x75, 0x29, 0x8b, 0xb2, 0xef, 0x6a,
	0x12, 0x0d, 0x21, 0x7e, 0x03, 0x6e, 0xc1, 0x35, 0xb3, 0xa3, 0x3a, 0x3d, 0x7b, 0x3a, 0xf4, 0xde,
	0x29, 0x46, 0xef, 0xb8, 0x66, 0x6d, 0x0c, 0xdb, 0x8e, 0x5f, 0x82, 0x77, 0xc5, 0x34, 0xdb, 0x32,
	0xc5, 0x4d, 0x0e, 0x93, 0xfb, 0xf1, 0xf0, 0x6e, 0x12, 0xa7, 0xb4, 0xef, 0x59, 0xfd, 0x42, 0xe0,
	0x9a, 0x57, 0x70, 0x08, 0xf3, 0x8c, 0x0b, 0x5e, 0x31, 0x9d, 0x4b, 0x91, 0x26, 0xed, 0x2c, 0x07,
	0x0c, 0x13, 0x80, 0x5c, 0x28, 0xcd, 0xc4, 0x25, 0x4f, 0x13, 0x6b, 0xcd, 0xa3, 0x47, 0x04, 0xaf,
	0x60, 0xb6, 0x93, 0x4a, 0xdb, 0x7f, 0xe1, 0xd8, 0xd3, 0x7f, 0xb5, 0x99, 0xe3, 0xbe, 0xb8, 0xda,
	0x7e, 0xf8, 0x62, 0x1e, 0x37, 0x91, 0x1d, 0xda, 0x83, 0xff, 0x97, 0xe0, 0xe4, 0xa1, 0x25, 0x08,
	0x61, 0xde, 0x39, 0xbf, 0x30, 0x1a, 0xd3, 0xc6, 0xe3, 0x31, 0x7b, 0xeb, 0xce, 0x26, 0xcb, 0x69,
	0x1c, 0xdc, 0xdd, 0x13, 0xf4, 0xe7, 0x9e, 0xa0, 0x9f, 0x35, 0x41, 0x37, 0x35, 0x41, 0xb7, 0x35,
	0x41, 0x77, 0x35, 0x41, 0xdf, 0x0f, 0x64, 0x74, 0x7b, 0x20, 0xa3, 0xed, 0xc4, 0xee, 0xea, 0xeb,
	0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa1, 0x80, 0x3b, 0x41, 0xd7, 0x02, 0x00, 0x00,
}

func (this *KV) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*KV)
	if !ok {
		that2, ok := that.(KV)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *KV")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *KV but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *KV but is not nil && this == nil")
	}
	if !bytes.Equal(this.Key, that1.Key) {
		return fmt.Errorf("Key this(%v) Not Equal that(%v)", this.Key, that1.Key)
	}
	if !bytes.Equal(this.Value, that1.Value) {
		return fmt.Errorf("Value this(%v) Not Equal that(%v)", this.Value, that1.Value)
	}
	if this.TimestampNano != that1.TimestampNano {
		return fmt.Errorf("TimestampNano this(%v) Not Equal that(%v)", this.TimestampNano, that1.TimestampNano)
	}
	if this.Flags != that1.Flags {
		return fmt.Errorf("Flags this(%v) Not Equal that(%v)", this.Flags, that1.Flags)
	}
	return nil
}
func (this *KV) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*KV)
	if !ok {
		that2, ok := that.(KV)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.Key, that1.Key) {
		return false
	}
	if !bytes.Equal(this.Value, that1.Value) {
		return false
	}
	if this.TimestampNano != that1.TimestampNano {
		return false
	}
	if this.Flags != that1.Flags {
		return false
	}
	return true
}
func (this *DBI) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*DBI)
	if !ok {
		that2, ok := that.(DBI)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *DBI")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *DBI but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *DBI but is not nil && this == nil")
	}
	if this.Name != that1.Name {
		return fmt.Errorf("Name this(%v) Not Equal that(%v)", this.Name, that1.Name)
	}
	if len(this.Entries) != len(that1.Entries) {
		return fmt.Errorf("Entries this(%v) Not Equal that(%v)", len(this.Entries), len(that1.Entries))
	}
	for i := range this.Entries {
		if !this.Entries[i].Equal(&that1.Entries[i]) {
			return fmt.Errorf("Entries this[%v](%v) Not Equal that[%v](%v)", i, this.Entries[i], i, that1.Entries[i])
		}
	}
	if this.Flags != that1.Flags {
		return fmt.Errorf("Flags this(%v) Not Equal that(%v)", this.Flags, that1.Flags)
	}
	if this.Transform != that1.Transform {
		return fmt.Errorf("Transform this(%v) Not Equal that(%v)", this.Transform, that1.Transform)
	}
	return nil
}
func (this *DBI) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DBI)
	if !ok {
		that2, ok := that.(DBI)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if len(this.Entries) != len(that1.Entries) {
		return false
	}
	for i := range this.Entries {
		if !this.Entries[i].Equal(&that1.Entries[i]) {
			return false
		}
	}
	if this.Flags != that1.Flags {
		return false
	}
	if this.Transform != that1.Transform {
		return false
	}
	return true
}
func (this *Snapshot) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*Snapshot)
	if !ok {
		that2, ok := that.(Snapshot)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *Snapshot")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *Snapshot but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *Snapshot but is not nil && this == nil")
	}
	if this.FormatVersion != that1.FormatVersion {
		return fmt.Errorf("FormatVersion this(%v) Not Equal that(%v)", this.FormatVersion, that1.FormatVersion)
	}
	if this.CompatVersion != that1.CompatVersion {
		return fmt.Errorf("CompatVersion this(%v) Not Equal that(%v)", this.CompatVersion, that1.CompatVersion)
	}
	if !this.Meta.Equal(&that1.Meta) {
		return fmt.Errorf("Meta this(%v) Not Equal that(%v)", this.Meta, that1.Meta)
	}
	if len(this.Databases) != len(that1.Databases) {
		return fmt.Errorf("Databases this(%v) Not Equal that(%v)", len(this.Databases), len(that1.Databases))
	}
	for i := range this.Databases {
		if !this.Databases[i].Equal(that1.Databases[i]) {
			return fmt.Errorf("Databases this[%v](%v) Not Equal that[%v](%v)", i, this.Databases[i], i, that1.Databases[i])
		}
	}
	return nil
}
func (this *Snapshot) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Snapshot)
	if !ok {
		that2, ok := that.(Snapshot)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.FormatVersion != that1.FormatVersion {
		return false
	}
	if this.CompatVersion != that1.CompatVersion {
		return false
	}
	if !this.Meta.Equal(&that1.Meta) {
		return false
	}
	if len(this.Databases) != len(that1.Databases) {
		return false
	}
	for i := range this.Databases {
		if !this.Databases[i].Equal(that1.Databases[i]) {
			return false
		}
	}
	return true
}
func (this *Snapshot_Meta) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*Snapshot_Meta)
	if !ok {
		that2, ok := that.(Snapshot_Meta)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *Snapshot_Meta")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *Snapshot_Meta but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *Snapshot_Meta but is not nil && this == nil")
	}
	if this.GenerationID != that1.GenerationID {
		return fmt.Errorf("GenerationID this(%v) Not Equal that(%v)", this.GenerationID, that1.GenerationID)
	}
	if this.InstanceID != that1.InstanceID {
		return fmt.Errorf("InstanceID this(%v) Not Equal that(%v)", this.InstanceID, that1.InstanceID)
	}
	if this.Hostname != that1.Hostname {
		return fmt.Errorf("Hostname this(%v) Not Equal that(%v)", this.Hostname, that1.Hostname)
	}
	if this.LmdbTxnID != that1.LmdbTxnID {
		return fmt.Errorf("LmdbTxnID this(%v) Not Equal that(%v)", this.LmdbTxnID, that1.LmdbTxnID)
	}
	if this.TimestampNano != that1.TimestampNano {
		return fmt.Errorf("TimestampNano this(%v) Not Equal that(%v)", this.TimestampNano, that1.TimestampNano)
	}
	if this.DatabaseName != that1.DatabaseName {
		return fmt.Errorf("DatabaseName this(%v) Not Equal that(%v)", this.DatabaseName, that1.DatabaseName)
	}
	return nil
}
func (this *Snapshot_Meta) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Snapshot_Meta)
	if !ok {
		that2, ok := that.(Snapshot_Meta)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.GenerationID != that1.GenerationID {
		return false
	}
	if this.InstanceID != that1.InstanceID {
		return false
	}
	if this.Hostname != that1.Hostname {
		return false
	}
	if this.LmdbTxnID != that1.LmdbTxnID {
		return false
	}
	if this.TimestampNano != that1.TimestampNano {
		return false
	}
	if this.DatabaseName != that1.DatabaseName {
		return false
	}
	return true
}
func (m *KV) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *KV) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *KV) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Flags != 0 {
		i = encodeVarintSnapshot(dAtA, i, uint64(m.Flags))
		i--
		dAtA[i] = 0x20
	}
	if m.TimestampNano != 0 {
		i -= 8
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(m.TimestampNano))
		i--
		dAtA[i] = 0x19
	}
	if len(m.Value) > 0 {
		i -= len(m.Value)
		copy(dAtA[i:], m.Value)
		i = encodeVarintSnapshot(dAtA, i, uint64(len(m.Value)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Key) > 0 {
		i -= len(m.Key)
		copy(dAtA[i:], m.Key)
		i = encodeVarintSnapshot(dAtA, i, uint64(len(m.Key)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *DBI) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DBI) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DBI) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Transform) > 0 {
		i -= len(m.Transform)
		copy(dAtA[i:], m.Transform)
		i = encodeVarintSnapshot(dAtA, i, uint64(len(m.Transform)))
		i--
		dAtA[i] = 0x22
	}
	if m.Flags != 0 {
		i = encodeVarintSnapshot(dAtA, i, uint64(m.Flags))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Entries) > 0 {
		for iNdEx := len(m.Entries) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Entries[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSnapshot(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintSnapshot(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Snapshot) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Snapshot) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Snapshot) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CompatVersion != 0 {
		i = encodeVarintSnapshot(dAtA, i, uint64(m.CompatVersion))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Databases) > 0 {
		for iNdEx := len(m.Databases) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Databases[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSnapshot(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	{
		size, err := m.Meta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintSnapshot(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.FormatVersion != 0 {
		i = encodeVarintSnapshot(dAtA, i, uint64(m.FormatVersion))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Snapshot_Meta) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Snapshot_Meta) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Snapshot_Meta) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DatabaseName) > 0 {
		i -= len(m.DatabaseName)
		copy(dAtA[i:], m.DatabaseName)
		i = encodeVarintSnapshot(dAtA, i, uint64(len(m.DatabaseName)))
		i--
		dAtA[i] = 0x3a
	}
	if m.TimestampNano != 0 {
		i -= 8
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(m.TimestampNano))
		i--
		dAtA[i] = 0x29
	}
	if m.LmdbTxnID != 0 {
		i = encodeVarintSnapshot(dAtA, i, uint64(m.LmdbTxnID))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Hostname) > 0 {
		i -= len(m.Hostname)
		copy(dAtA[i:], m.Hostname)
		i = encodeVarintSnapshot(dAtA, i, uint64(len(m.Hostname)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.InstanceID) > 0 {
		i -= len(m.InstanceID)
		copy(dAtA[i:], m.InstanceID)
		i = encodeVarintSnapshot(dAtA, i, uint64(len(m.InstanceID)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.GenerationID) > 0 {
		i -= len(m.GenerationID)
		copy(dAtA[i:], m.GenerationID)
		i = encodeVarintSnapshot(dAtA, i, uint64(len(m.GenerationID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintSnapshot(dAtA []byte, offset int, v uint64) int {
	offset -= sovSnapshot(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func NewPopulatedKV(r randySnapshot, easy bool) *KV {
	this := &KV{}
	v1 := r.Intn(100)
	this.Key = make([]byte, v1)
	for i := 0; i < v1; i++ {
		this.Key[i] = byte(r.Intn(256))
	}
	v2 := r.Intn(100)
	this.Value = make([]byte, v2)
	for i := 0; i < v2; i++ {
		this.Value[i] = byte(r.Intn(256))
	}
	this.TimestampNano = uint64(uint64(r.Uint32()))
	this.Flags = uint32(r.Uint32())
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedDBI(r randySnapshot, easy bool) *DBI {
	this := &DBI{}
	this.Name = string(randStringSnapshot(r))
	if r.Intn(5) != 0 {
		v3 := r.Intn(5)
		this.Entries = make([]KV, v3)
		for i := 0; i < v3; i++ {
			v4 := NewPopulatedKV(r, easy)
			this.Entries[i] = *v4
		}
	}
	this.Flags = uint64(uint64(r.Uint32()))
	this.Transform = string(randStringSnapshot(r))
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedSnapshot(r randySnapshot, easy bool) *Snapshot {
	this := &Snapshot{}
	this.FormatVersion = uint32(r.Uint32())
	v5 := NewPopulatedSnapshot_Meta(r, easy)
	this.Meta = *v5
	if r.Intn(5) != 0 {
		v6 := r.Intn(5)
		this.Databases = make([]*DBI, v6)
		for i := 0; i < v6; i++ {
			this.Databases[i] = NewPopulatedDBI(r, easy)
		}
	}
	this.CompatVersion = uint32(r.Uint32())
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedSnapshot_Meta(r randySnapshot, easy bool) *Snapshot_Meta {
	this := &Snapshot_Meta{}
	this.GenerationID = string(randStringSnapshot(r))
	this.InstanceID = string(randStringSnapshot(r))
	this.Hostname = string(randStringSnapshot(r))
	this.LmdbTxnID = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.LmdbTxnID *= -1
	}
	this.TimestampNano = uint64(uint64(r.Uint32()))
	this.DatabaseName = string(randStringSnapshot(r))
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

type randySnapshot interface {
	Float32() float32
	Float64() float64
	Int63() int64
	Int31() int32
	Uint32() uint32
	Intn(n int) int
}

func randUTF8RuneSnapshot(r randySnapshot) rune {
	ru := r.Intn(62)
	if ru < 10 {
		return rune(ru + 48)
	} else if ru < 36 {
		return rune(ru + 55)
	}
	return rune(ru + 61)
}
func randStringSnapshot(r randySnapshot) string {
	v7 := r.Intn(100)
	tmps := make([]rune, v7)
	for i := 0; i < v7; i++ {
		tmps[i] = randUTF8RuneSnapshot(r)
	}
	return string(tmps)
}
func randUnrecognizedSnapshot(r randySnapshot, maxFieldNumber int) (dAtA []byte) {
	l := r.Intn(5)
	for i := 0; i < l; i++ {
		wire := r.Intn(4)
		if wire == 3 {
			wire = 5
		}
		fieldNumber := maxFieldNumber + r.Intn(100)
		dAtA = randFieldSnapshot(dAtA, r, fieldNumber, wire)
	}
	return dAtA
}
func randFieldSnapshot(dAtA []byte, r randySnapshot, fieldNumber int, wire int) []byte {
	key := uint32(fieldNumber)<<3 | uint32(wire)
	switch wire {
	case 0:
		dAtA = encodeVarintPopulateSnapshot(dAtA, uint64(key))
		v8 := r.Int63()
		if r.Intn(2) == 0 {
			v8 *= -1
		}
		dAtA = encodeVarintPopulateSnapshot(dAtA, uint64(v8))
	case 1:
		dAtA = encodeVarintPopulateSnapshot(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	case 2:
		dAtA = encodeVarintPopulateSnapshot(dAtA, uint64(key))
		ll := r.Intn(100)
		dAtA = encodeVarintPopulateSnapshot(dAtA, uint64(ll))
		for j := 0; j < ll; j++ {
			dAtA = append(dAtA, byte(r.Intn(256)))
		}
	default:
		dAtA = encodeVarintPopulateSnapshot(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	}
	return dAtA
}
func encodeVarintPopulateSnapshot(dAtA []byte, v uint64) []byte {
	for v >= 1<<7 {
		dAtA = append(dAtA, uint8(uint64(v)&0x7f|0x80))
		v >>= 7
	}
	dAtA = append(dAtA, uint8(v))
	return dAtA
}
func (m *KV) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Key)
	if l > 0 {
		n += 1 + l + sovSnapshot(uint64(l))
	}
	l = len(m.Value)
	if l > 0 {
		n += 1 + l + sovSnapshot(uint64(l))
	}
	if m.TimestampNano != 0 {
		n += 9
	}
	if m.Flags != 0 {
		n += 1 + sovSnapshot(uint64(m.Flags))
	}
	return n
}

func (m *DBI) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovSnapshot(uint64(l))
	}
	if len(m.Entries) > 0 {
		for _, e := range m.Entries {
			l = e.Size()
			n += 1 + l + sovSnapshot(uint64(l))
		}
	}
	if m.Flags != 0 {
		n += 1 + sovSnapshot(uint64(m.Flags))
	}
	l = len(m.Transform)
	if l > 0 {
		n += 1 + l + sovSnapshot(uint64(l))
	}
	return n
}

func (m *Snapshot) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.FormatVersion != 0 {
		n += 1 + sovSnapshot(uint64(m.FormatVersion))
	}
	l = m.Meta.Size()
	n += 1 + l + sovSnapshot(uint64(l))
	if len(m.Databases) > 0 {
		for _, e := range m.Databases {
			l = e.Size()
			n += 1 + l + sovSnapshot(uint64(l))
		}
	}
	if m.CompatVersion != 0 {
		n += 1 + sovSnapshot(uint64(m.CompatVersion))
	}
	return n
}

func (m *Snapshot_Meta) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.GenerationID)
	if l > 0 {
		n += 1 + l + sovSnapshot(uint64(l))
	}
	l = len(m.InstanceID)
	if l > 0 {
		n += 1 + l + sovSnapshot(uint64(l))
	}
	l = len(m.Hostname)
	if l > 0 {
		n += 1 + l + sovSnapshot(uint64(l))
	}
	if m.LmdbTxnID != 0 {
		n += 1 + sovSnapshot(uint64(m.LmdbTxnID))
	}
	if m.TimestampNano != 0 {
		n += 9
	}
	l = len(m.DatabaseName)
	if l > 0 {
		n += 1 + l + sovSnapshot(uint64(l))
	}
	return n
}

func sovSnapshot(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSnapshot(x uint64) (n int) {
	return sovSnapshot(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *KV) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSnapshot
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: KV: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: KV: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSnapshot
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSnapshot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = append(m.Key[:0], dAtA[iNdEx:postIndex]...)
			if m.Key == nil {
				m.Key = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSnapshot
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSnapshot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Value = append(m.Value[:0], dAtA[iNdEx:postIndex]...)
			if m.Value == nil {
				m.Value = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimestampNano", wireType)
			}
			m.TimestampNano = 0
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			m.TimestampNano = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Flags", wireType)
			}
			m.Flags = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Flags |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSnapshot(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSnapshot
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DBI) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSnapshot
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DBI: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DBI: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSnapshot
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSnapshot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Entries", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSnapshot
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSnapshot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Entries = append(m.Entries, KV{})
			if err := m.Entries[len(m.Entries)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Flags", wireType)
			}
			m.Flags = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Flags |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Transform", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSnapshot
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSnapshot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Transform = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSnapshot(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSnapshot
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Snapshot) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSnapshot
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Snapshot: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Snapshot: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FormatVersion", wireType)
			}
			m.FormatVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FormatVersion |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Meta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSnapshot
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSnapshot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Meta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Databases", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSnapshot
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSnapshot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Databases = append(m.Databases, &DBI{})
			if err := m.Databases[len(m.Databases)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CompatVersion", wireType)
			}
			m.CompatVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CompatVersion |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSnapshot(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSnapshot
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Snapshot_Meta) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSnapshot
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Meta: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Meta: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GenerationID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSnapshot
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSnapshot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GenerationID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InstanceID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSnapshot
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSnapshot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InstanceID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hostname", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSnapshot
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSnapshot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hostname = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LmdbTxnID", wireType)
			}
			m.LmdbTxnID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LmdbTxnID |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimestampNano", wireType)
			}
			m.TimestampNano = 0
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			m.TimestampNano = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DatabaseName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSnapshot
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSnapshot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DatabaseName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSnapshot(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSnapshot
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSnapshot(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSnapshot
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSnapshot
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSnapshot
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSnapshot
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSnapshot        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSnapshot          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSnapshot = fmt.Errorf("proto: unexpected end of group")
)
