---
name: Build and push Docker image

on:
  workflow_dispatch:
    inputs:
      platforms:
        description: platforms to build for
        type: string
        default: linux/amd64,linux/arm64/v8
        required: false
      image-name:
        description: a base name for image tags
        type: string
        default: lightningstream
        required: false
      image-tags:
        description: image tags
        type: string
        default: type=semver,pattern={{version}}
        required: false
      push:
        description: push image to Docker Hub
        type: boolean
        required: true
    secrets:
      DOCKERHUB_ORGANIZATION_NAME:
        required: true
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

permissions:
  contents: read # principle of least privilege

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx for multi-platform builds
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ inputs.platforms }}
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Derive image tag(s)
        uses: docker/metadata-action@v5
        with:
          images: >-
            ${{ secrets.DOCKERHUB_ORGANIZATION_NAME }}/${{ inputs.image-name }}
          tags: ${{ inputs.image-tags }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ inputs.platforms }}
          push: ${{ inputs.push }}
          sbom: true
          tags: ${{ env.DOCKER_METADATA_OUTPUT_TAGS }}
